import json
import os

surah_data = [
    (1,  "الفاتحة",    "Al-Fatihah",    "meccan",  7),
    (2,  "البقرة",     "Al-Baqarah",    "medinan", 286),
    (3,  "آل عمران",   "Ali 'Imran",    "medinan", 200),
    (4,  "النساء",     "An-Nisa",       "medinan", 176),
    (5,  "المائدة",    "Al-Maidah",     "medinan", 120),
    (6,  "الأنعام",    "Al-Anam",       "meccan",  165),
    (7,  "الأعراف",    "Al-Araf",       "meccan",  206),
    (8,  "الأنفال",    "Al-Anfal",      "medinan", 75),
    (9,  "التوبة",     "At-Tawbah",     "medinan", 129),
    (10, "يونس",       "Yunus",         "meccan",  109),
    (11, "هود",        "Hud",           "meccan",  123),
    (12, "يوسف",       "Yusuf",         "meccan",  111),
    (13, "الرعد",      "Ar-Rad",        "medinan", 43),
    (14, "إبراهيم",    "Ibrahim",       "meccan",  52),
    (15, "الحجر",      "Al-Hijr",       "meccan",  99),
    (16, "النحل",      "An-Nahl",       "meccan",  128),
    (17, "الإسراء",    "Al-Isra",       "meccan",  111),
    (18, "الكهف",      "Al-Kahf",       "meccan",  110),
    (19, "مريم",       "Maryam",        "meccan",  98),
    (20, "طه",         "Ta-Ha",         "meccan",  135),
    (21, "الأنبياء",   "Al-Anbiya",     "meccan",  112),
    (22, "الحج",       "Al-Hajj",       "medinan", 78),
    (23, "المؤمنون",   "Al-Muminun",    "meccan",  118),
    (24, "النور",      "An-Nur",        "medinan", 64),
    (25, "الفرقان",    "Al-Furqan",     "meccan",  77),
    (26, "الشعراء",    "Ash-Shuara",    "meccan",  227),
    (27, "النمل",      "An-Naml",       "meccan",  93),
    (28, "القصص",      "Al-Qasas",      "meccan",  88),
    (29, "العنكبوت",   "Al-Ankabut",    "meccan",  69),
    (30, "الروم",      "Ar-Rum",        "meccan",  60),
    (31, "لقمان",      "Luqman",        "meccan",  34),
    (32, "السجدة",     "As-Sajdah",     "meccan",  30),
    (33, "الأحزاب",    "Al-Ahzab",      "medinan", 73),
    (34, "سبأ",        "Saba",          "meccan",  54),
    (35, "فاطر",       "Fatir",         "meccan",  45),
    (36, "يس",         "Ya-Sin",        "meccan",  83),
    (37, "الصافات",    "As-Saffat",     "meccan",  182),
    (38, "ص",          "Sad",           "meccan",  88),
    (39, "الزمر",      "Az-Zumar",      "meccan",  75),
    (40, "غافر",       "Ghafir",        "meccan",  85),
    (41, "فصلت",       "Fussilat",      "meccan",  54),
    (42, "الشورى",     "Ash-Shura",     "meccan",  53),
    (43, "الزخرف",     "Az-Zukhruf",    "meccan",  89),
    (44, "الدخان",     "Ad-Dukhan",     "meccan",  59),
    (45, "الجاثية",    "Al-Jathiyah",   "meccan",  37),
    (46, "الأحقاف",    "Al-Ahqaf",      "meccan",  35),
    (47, "محمد",       "Muhammad",      "medinan", 38),
    (48, "الفتح",      "Al-Fath",       "medinan", 29),
    (49, "الحجرات",    "Al-Hujurat",    "medinan", 18),
    (50, "ق",          "Qaf",           "meccan",  45),
    (51, "الذاريات",   "Adh-Dhariyat",  "meccan",  60),
    (52, "الطور",      "At-Tur",        "meccan",  49),
    (53, "النجم",      "An-Najm",       "meccan",  62),
    (54, "القمر",      "Al-Qamar",      "meccan",  55),
    (55, "الرحمن",     "Ar-Rahman",     "medinan", 78),
    (56, "الواقعة",    "Al-Waqiah",     "meccan",  96),
    (57, "الحديد",     "Al-Hadid",      "medinan", 29),
    (58, "المجادلة",   "Al-Mujadila",   "medinan", 22),
    (59, "الحشر",      "Al-Hashr",      "medinan", 24),
    (60, "الممتحنة",   "Al-Mumtahanah", "medinan", 13),
    (61, "الصف",       "As-Saf",        "medinan", 14),
    (62, "الجمعة",     "Al-Jumuah",     "medinan", 11),
    (63, "المنافقون",  "Al-Munafiqun",  "medinan", 11),
    (64, "التغابن",    "At-Taghabun",   "medinan", 18),
    (65, "الطلاق",     "At-Talaq",      "medinan", 12),
    (66, "التحريم",    "At-Tahrim",     "medinan", 12),
    (67, "الملك",      "Al-Mulk",       "meccan",  30),
    (68, "القلم",      "Al-Qalam",      "meccan",  52),
    (69, "الحاقة",     "Al-Haqqah",     "meccan",  52),
    (70, "المعارج",    "Al-Maarij",     "meccan",  44),
    (71, "نوح",        "Nuh",           "meccan",  28),
    (72, "الجن",       "Al-Jinn",       "meccan",  28),
    (73, "المزمل",     "Al-Muzzammil",  "meccan",  20),
    (74, "المدثر",     "Al-Muddaththir","meccan",  56),
    (75, "القيامة",    "Al-Qiyamah",    "meccan",  40),
    (76, "الإنسان",    "Al-Insan",      "medinan", 31),
    (77, "المرسلات",   "Al-Mursalat",   "meccan",  50),
    (78, "النبأ",      "An-Naba",       "meccan",  40),
    (79, "النازعات",   "An-Naziat",     "meccan",  46),
    (80, "عبس",        "Abasa",         "meccan",  42),
    (81, "التكوير",    "At-Takwir",     "meccan",  29),
    (82, "الانفطار",   "Al-Infitar",    "meccan",  19),
    (83, "المطففين",   "Al-Mutaffifin", "meccan",  36),
    (84, "الانشقاق",   "Al-Inshiqaq",   "meccan",  25),
    (85, "البروج",     "Al-Buruj",      "meccan",  22),
    (86, "الطارق",     "At-Tariq",      "meccan",  17),
    (87, "الأعلى",     "Al-Ala",        "meccan",  19),
    (88, "الغاشية",    "Al-Ghashiyah",  "meccan",  26),
    (89, "الفجر",      "Al-Fajr",       "meccan",  30),
    (90, "البلد",      "Al-Balad",      "meccan",  20),
    (91, "الشمس",      "Ash-Shams",     "meccan",  15),
    (92, "الليل",      "Al-Layl",       "meccan",  21),
    (93, "الضحى",      "Ad-Duhaa",      "meccan",  11),
    (94, "الشرح",      "Ash-Sharh",     "meccan",  8),
    (95, "التين",      "At-Tin",        "meccan",  8),
    (96, "العلق",      "Al-Alaq",       "meccan",  19),
    (97, "القدر",      "Al-Qadr",       "meccan",  5),
    (98, "البينة",     "Al-Bayyinah",   "medinan", 8),
    (99, "الزلزلة",    "Az-Zalzalah",   "medinan", 8),
    (100,"العاديات",   "Al-Adiyat",     "meccan",  11),
    (101,"القارعة",    "Al-Qariah",     "meccan",  11),
    (102,"التكاثر",    "At-Takathur",   "meccan",  8),
    (103,"العصر",      "Al-Asr",        "meccan",  3),
    (104,"الهمزة",     "Al-Humazah",    "meccan",  9),
    (105,"الفيل",      "Al-Fil",        "meccan",  5),
    (106,"قريش",       "Quraysh",       "meccan",  4),
    (107,"الماعون",    "Al-Maun",       "meccan",  7),
    (108,"الكوثر",     "Al-Kawthar",    "meccan",  3),
    (109,"الكافرون",   "Al-Kafirun",    "meccan",  6),
    (110,"النصر",      "An-Nasr",       "medinan", 3),
    (111,"المسد",      "Al-Masad",      "meccan",  5),
    (112,"الإخلاص",    "Al-Ikhlas",     "meccan",  4),
    (113,"الفلق",      "Al-Falaq",      "meccan",  5),
    (114,"الناس",      "An-Nas",        "meccan",  6),
]

# Complete verses for specified surahs (with full diacritics/tashkeel)
full_verses = {
    1: [
        {"id": 1, "text": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"},
        {"id": 2, "text": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ"},
        {"id": 3, "text": "الرَّحْمَٰنِ الرَّحِيمِ"},
        {"id": 4, "text": "مَالِكِ يَوْمِ الدِّينِ"},
        {"id": 5, "text": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ"},
        {"id": 6, "text": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ"},
        {"id": 7, "text": "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ"},
    ],
    97: [
        {"id": 1, "text": "إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ"},
        {"id": 2, "text": "وَمَا أَدْرَاكَ مَا لَيْلَةُ الْقَدْرِ"},
        {"id": 3, "text": "لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ"},
        {"id": 4, "text": "تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ"},
        {"id": 5, "text": "سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ"},
    ],
    99: [
        {"id": 1, "text": "إِذَا زُلْزِلَتِ الْأَرْضُ زِلْزَالَهَا"},
        {"id": 2, "text": "وَأَخْرَجَتِ الْأَرْضُ أَثْقَالَهَا"},
        {"id": 3, "text": "وَقَالَ الْإِنسَانُ مَا لَهَا"},
        {"id": 4, "text": "يَوْمَئِذٍ تُحَدِّثُ أَخْبَارَهَا"},
        {"id": 5, "text": "بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا"},
        {"id": 6, "text": "يَوْمَئِذٍ يَصْدُرُ النَّاسُ أَشْتَاتًا لِّيُرَوْا أَعْمَالَهُمْ"},
        {"id": 7, "text": "فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ"},
        {"id": 8, "text": "وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ"},
    ],
    103: [
        {"id": 1, "text": "وَالْعَصْرِ"},
        {"id": 2, "text": "إِنَّ الْإِنسَانَ لَفِي خُسْرٍ"},
        {"id": 3, "text": "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ"},
    ],
    105: [
        {"id": 1, "text": "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ"},
        {"id": 2, "text": "أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ"},
        {"id": 3, "text": "وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ"},
        {"id": 4, "text": "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ"},
        {"id": 5, "text": "فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ"},
    ],
    106: [
        {"id": 1, "text": "لِإِيلَافِ قُرَيْشٍ"},
        {"id": 2, "text": "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ"},
        {"id": 3, "text": "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ"},
        {"id": 4, "text": "الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ"},
    ],
    107: [
        {"id": 1, "text": "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ"},
        {"id": 2, "text": "فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ"},
        {"id": 3, "text": "وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ"},
        {"id": 4, "text": "فَوَيْلٌ لِّلْمُصَلِّينَ"},
        {"id": 5, "text": "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ"},
        {"id": 6, "text": "الَّذِينَ هُمْ يُرَاءُونَ"},
        {"id": 7, "text": "وَيَمْنَعُونَ الْمَاعُونَ"},
    ],
    108: [
        {"id": 1, "text": "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ"},
        {"id": 2, "text": "فَصَلِّ لِرَبِّكَ وَانْحَرْ"},
        {"id": 3, "text": "إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ"},
    ],
    109: [
        {"id": 1, "text": "قُلْ يَا أَيُّهَا الْكَافِرُونَ"},
        {"id": 2, "text": "لَا أَعْبُدُ مَا تَعْبُدُونَ"},
        {"id": 3, "text": "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ"},
        {"id": 4, "text": "وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ"},
        {"id": 5, "text": "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ"},
        {"id": 6, "text": "لَكُمْ دِينُكُمْ وَلِيَ دِينِ"},
    ],
    110: [
        {"id": 1, "text": "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ"},
        {"id": 2, "text": "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا"},
        {"id": 3, "text": "فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا"},
    ],
    111: [
        {"id": 1, "text": "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ"},
        {"id": 2, "text": "مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ"},
        {"id": 3, "text": "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ"},
        {"id": 4, "text": "وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ"},
        {"id": 5, "text": "فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ"},
    ],
    112: [
        {"id": 1, "text": "قُلْ هُوَ اللَّهُ أَحَدٌ"},
        {"id": 2, "text": "اللَّهُ الصَّمَدُ"},
        {"id": 3, "text": "لَمْ يَلِدْ وَلَمْ يُولَدْ"},
        {"id": 4, "text": "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ"},
    ],
    113: [
        {"id": 1, "text": "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ"},
        {"id": 2, "text": "مِن شَرِّ مَا خَلَقَ"},
        {"id": 3, "text": "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ"},
        {"id": 4, "text": "وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ"},
        {"id": 5, "text": "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ"},
    ],
    114: [
        {"id": 1, "text": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ"},
        {"id": 2, "text": "مَلِكِ النَّاسِ"},
        {"id": 3, "text": "إِلَٰهِ النَّاسِ"},
        {"id": 4, "text": "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ"},
        {"id": 5, "text": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ"},
        {"id": 6, "text": "مِنَ الْجِنَّةِ وَالنَّاسِ"},
    ],
}

quran = []
for (sid, name, trans, stype, total) in surah_data:
    verses = full_verses.get(sid, [])
    quran.append({
        "id": sid,
        "name": name,
        "transliteration": trans,
        "type": stype,
        "total_verses": total,
        "verses": verses,
    })

output_path = "/home/user/as/assets/quran.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(quran, f, ensure_ascii=False, indent=2)

size = os.path.getsize(output_path)
print(f"File written: {output_path}")
print(f"File size: {size:,} bytes")

with open(output_path, "r", encoding="utf-8") as f:
    head = f.read(300)
print(f"\nFirst 300 characters:\n{head}")

# Verify surah count and spot-check
print(f"\nTotal surahs in file: {len(quran)}")
print(f"First surah: {quran[0]['name']} ({quran[0]['transliteration']}) — {len(quran[0]['verses'])} verses")
print(f"Surah 97 (Al-Qadr): {len(quran[96]['verses'])} verses")
print(f"Surah 112 (Al-Ikhlas): {len(quran[111]['verses'])} verses")
print(f"Surah 114 (An-Nas): {len(quran[113]['verses'])} verses")
print(f"Surah 2 (Al-Baqarah) verses array: {quran[1]['verses']} (should be empty)")
